import 'dart:async';
import 'dart:math' as math;
import 'dart:ui' as ui;

import 'package:flutter/material.dart' hide Text, TextSpan;
import 'package:flutter/scheduler.dart';
import 'package:flutter/services.dart';
import 'package:salamlearn/logic/localization/app_translations.dart';

import '../../../data/letter_trace_data.dart';
import '../../../data/models/curriculum/curriculum_models.dart';
import '../../widgets/letter_trace_canvas.dart';
import 'trace_audio.dart';

/// FR-4.1's Tactile Recognition Engine — tracks the learner's continuous
/// drag (X/Y samples) and validates it against a predefined right-to-left
/// vector path drawn in the actual shape of the Arabic letter on the card.
///
/// Each letter's shape and stroke paths come from the bundled ScheherazadeNew
/// Bold font's own isolated-form glyph (`lib/data/letter_trace_data.dart`, generated by
/// `dumps/tracing_layers/gen_letter_paths.py`): the outline is the tracing
/// mask, and the paths run along the glyph's centre in writing order.

class TraceActivity extends StatefulWidget {
  const TraceActivity({
    super.key,
    required this.cards,
    required this.xp,
    required this.color,
    required this.onComplete,
    required this.onBack,
    this.audioEnabled = true,
  });

  final List<FlashCard> cards;
  final int xp;
  final Color color;
  final void Function(int xp, double accuracyPct, int errors) onComplete;

  /// `LessonPlayerScreen` skips its own top bar for trace (see its
  /// `_activity.type` switch) since this scene's back control is baked into
  /// its own scenery instead — the yellow circular arrow drawn here, not a
  /// bar-mounted one.
  final VoidCallback onBack;
  final bool audioEnabled;

  @override
  State<TraceActivity> createState() => _TraceActivityState();
}

class _TraceActivityState extends State<TraceActivity>
    with TickerProviderStateMixin {
  int _idx = 0;
  double _accuracy = 0.0;
  bool _checked = false;
  bool _passed = false;
  int _failedChecks = 0;

  /// Accuracy (0..1) each letter passed with, in order — the ending's tiles.
  final List<double> _scores = [];

  /// Time spent tracing this round, for the ending's summary.
  final _watch = Stopwatch();

  late final _entrance = AnimationController(
    vsync: this,
    duration: const Duration(milliseconds: 320),
  )..forward();
  late final _breathe = AnimationController(
    vsync: this,
    duration: const Duration(milliseconds: 2600),
  )..repeat(reverse: true);
  late final _wobble = AnimationController(
    vsync: this,
    duration: const Duration(milliseconds: 320),
  );

  /// Start screen idle loop (logo bob, Play pulse); stopped on Play.
  late final _idle = AnimationController(
    vsync: this,
    duration: const Duration(seconds: 4),
  )..repeat();
  _Screen _screen = _Screen.start;
  bool _playDown = false;

  /// Staggers the How to Play steps and the ending's stars in.
  late final _enter = AnimationController(
    vsync: this,
    duration: const Duration(milliseconds: 1400),
  );

  /// Per-letter countdown driving the HUD timer; paused once a letter
  /// passes. Visual pacing only: running out doesn't fail the letter.
  late final _clock = AnimationController(
    vsync: this,
    duration: const Duration(seconds: _kSeconds),
  );
  static const _kSeconds = 30;

  /// Sound button: off silences the game's clicks.
  bool _sound = true;

  /// Music button state.
  bool _music = true;
  TraceAudio? _audio;

  /// The courtyard backdrop, drawn live by `shaders/sand_tracer_bg.frag`
  /// once its layers load (the flat painting shows until then, or for good
  /// if shaders aren't available). [_bgT] is seconds since the screen opened.
  ui.FragmentShader? _bgShader;
  List<ui.Image>? _bgLayers;
  final _bgT = ValueNotifier<double>(0);
  late final Ticker _bgTicker = createTicker(
    (e) => _bgT.value = e.inMicroseconds / 1e6,
  );

  @override
  void initState() {
    super.initState();
    if (widget.audioEnabled) {
      _audio = TraceAudio();
      unawaited(_audio!.startMusic());
    }
    _bgTicker.start();
    _loadLiveBg();
  }

  Future<void> _loadLiveBg() async {
    try {
      final program = await ui.FragmentProgram.fromAsset(
        'shaders/sand_tracer_bg.frag',
      );
      final images = await Future.wait([
        for (final l in ['clean', 'palms', 'field', 'aux', 'clouds'])
          _decodeAsset('$_kA/bg_$l.png'),
      ]);
      if (!mounted) {
        for (final i in images) {
          i.dispose();
        }
        return;
      }
      setState(() {
        _bgShader = program.fragmentShader();
        _bgLayers = images;
      });
    } catch (_) {
      // Shaders unsupported here: the static art stays.
    }
  }

  static Future<ui.Image> _decodeAsset(String asset) async {
    final data = await rootBundle.load(asset);
    final codec = await ui.instantiateImageCodec(data.buffer.asUint8List());
    return (await codec.getNextFrame()).image;
  }

  /// Palms and bushes swaying in the wind, clouds drifting behind them.
  Widget _liveBg() {
    final shader = _bgShader;
    final layers = _bgLayers;
    if (shader == null ||
        layers == null ||
        MediaQuery.of(context).disableAnimations) {
      return Image.asset('$_kA/start_bg.png', fit: BoxFit.cover);
    }
    return RepaintBoundary(
      child: FittedBox(
        fit: BoxFit.cover,
        child: SizedBox(
          width: _kW,
          height: _kH,
          child: ValueListenableBuilder<double>(
            valueListenable: _bgT,
            builder: (context, t, _) =>
                CustomPaint(painter: _LiveBgPainter(shader, layers, t)),
          ),
        ),
      ),
    );
  }

  static const _overshoot = Cubic(0.34, 1.56, 0.64, 1.0);
  static const _passThreshold = 0.75;
  static const _autoPassThreshold = 0.97;

  FlashCard get _card => widget.cards[_idx];

  /// Extracts the actual Arabic letter from the card's `arabic` field.
  /// Cards follow the format `"أَلِف\nا"` where the line after `\n` is the
  /// standalone letter shape the learner should trace.
  String get _letter {
    final parts = _card.arabic.split('\n');
    return (parts.length > 1 ? parts.last : _card.arabic).trim();
  }

  /// Reference size used for tolerance math (`_computeAccuracy`) — a
  /// fraction of the *actual* canvas's shortest side, not a fixed px value,
  /// so it stays proportional no matter how big the tray ends up.
  double _boxSizeFor(Size size) => size.shortestSide * 0.78;

  LetterTrace? get _trace {
    var key = _letter;
    if (key == 'أ' || key == 'إ' || key == 'آ') key = 'ا';
    if (key == 'ة') key = 'ت';
    if (key == 'ى') key = 'ي';
    return letterTraces[key];
  }

  /// The tray's sand, traced off `game_tray.png` and put in the tracing
  /// canvas's own 638x499 stage units (the canvas covers the sand's bounds).
  /// It's a trapezoid, narrower at the top, so a plain rectangle would let
  /// the letter run over the frame.
  static const _kSandW = 638.0;
  static const _kSandH = 499.0;
  static const _kSandPoly = <double>[
    545, 26, 563, 70, 637, 413, 638, 439, 599, 488, 571, 496, 511, 499, //
    97, 499, 40, 487, 27, 476, 0, 434, 1, 409, 60, 138, 87, 36, 100, 15,
    113, 5, 131, 0, 486, 0, 521, 5,
  ];

  /// The sand's outline at the canvas's actual [size].
  static Path _sand(Size size) {
    final sx = size.width / _kSandW, sy = size.height / _kSandH;
    return Path()..addPolygon([
      for (var i = 0; i < _kSandPoly.length; i += 2)
        Offset(_kSandPoly[i] * sx, _kSandPoly[i + 1] * sy),
    ], true);
  }

  /// Last [_fit], reused across frames (it's asked for on every paint).
  (LetterTrace, Size, Offset Function(double, double))? _fitCache;

  /// Maps the letter's unit space onto [size]: centred on the sand and as
  /// large as it can be with its whole box, plus a margin for the outline's
  /// thickening and the number badges, still inside the sand.
  Offset Function(double x, double y) _fit(LetterTrace t, Size size) {
    final cached = _fitCache;
    if (cached != null && cached.$1 == t && cached.$2 == size) return cached.$3;
    var minX = double.infinity, maxX = -double.infinity;
    var minY = double.infinity, maxY = -double.infinity;
    for (final c in t.outline) {
      for (var i = 0; i < c.length; i += 2) {
        minX = math.min(minX, c[i]);
        maxX = math.max(maxX, c[i]);
        minY = math.min(minY, c[i + 1]);
        maxY = math.max(maxY, c[i + 1]);
      }
    }
    final w = maxX - minX, h = maxY - minY;
    final centre = Offset(size.width / 2, size.height * .52);
    final sand = _sand(size);
    final margin = 14 + size.shortestSide * .04;
    // The sand is convex, so the box fits if its four corners do.
    bool fits(double scale) {
      final hw = w * scale / 2 + margin, hh = h * scale / 2 + margin;
      return [
        centre + Offset(-hw, -hh),
        centre + Offset(hw, -hh),
        centre + Offset(-hw, hh),
        centre + Offset(hw, hh),
      ].every(sand.contains);
    }

    var lo = 0.0, hi = math.min(size.width / w, size.height / h);
    for (var i = 0; i < 24; i++) {
      final mid = (lo + hi) / 2;
      if (fits(mid)) {
        lo = mid;
      } else {
        hi = mid;
      }
    }
    final left = centre.dx - w * lo / 2 - minX * lo;
    final top = centre.dy - h * lo / 2 - minY * lo;
    Offset at(double x, double y) => Offset(left + x * lo, top + y * lo);
    _fitCache = (t, size, at);
    return at;
  }

  static List<Offset> _points(
    List<double> flat,
    Offset Function(double, double) at,
  ) => [for (var i = 0; i < flat.length; i += 2) at(flat[i], flat[i + 1])];

  List<List<Offset>> _guideStrokes(Size size) {
    final t = _trace;
    if (t == null) return [];
    final at = _fit(t, size);
    return [for (final s in t.strokes) _points(s, at)];
  }

  /// The letter's own outline at the same fit as [_guideStrokes].
  Path _glyph(Size size) {
    final path = Path();
    final t = _trace;
    if (t == null) return path;
    final at = _fit(t, size);
    for (final c in t.outline) {
      path.addPolygon(_points(c, at), true);
    }
    return path;
  }

  /// Accuracy per stroke blends two measures so both failure modes get
  /// caught: recall (how much of the guide the learner actually traced)
  /// and precision (how closely the learner's own marks stuck to the
  /// guide). Recall alone let a broad scribble across the whole card
  /// "cover" every guide point and score as a near-perfect trace, since
  /// nothing penalized ink that strayed off the letter. The average
  /// across strokes (including dots) keeps every stroke weighted
  /// equally so body strokes don't dominate the check.
  double _computeAccuracy(List<List<Offset>> userStrokes, Size canvasSize) {
    if (userStrokes.isEmpty) return 0.0;
    final guideStrokes = _guideStrokes(canvasSize);
    if (guideStrokes.isEmpty) return 0.0;
    final tolerance = _boxSizeFor(canvasSize) * 0.12;

    var totalScore = 0.0;
    for (var i = 0; i < guideStrokes.length; i++) {
      final guide = guideStrokes[i];
      if (guide.isEmpty) continue;
      if (i >= userStrokes.length) continue;
      final user = userStrokes[i];
      if (user.isEmpty) continue;

      var covered = 0;
      for (final gp in guide) {
        for (final up in user) {
          if ((up - gp).distance <= tolerance) {
            covered++;
            break;
          }
        }
      }
      final recall = covered / guide.length;

      var onPath = 0;
      for (final up in user) {
        for (final gp in guide) {
          if ((up - gp).distance <= tolerance) {
            onPath++;
            break;
          }
        }
      }
      final precision = onPath / user.length;

      totalScore += recall * 0.6 + precision * 0.4;
    }

    return totalScore / guideStrokes.length;
  }

  void _handleStroke(List<List<Offset>> userStrokes, Size canvasSize) {
    final acc = _computeAccuracy(userStrokes, canvasSize);
    setState(() => _accuracy = acc);
    if (acc >= _autoPassThreshold && !_passed) {
      setState(() {
        _checked = true;
        _passed = true;
      });
      _clock.stop();
    }
  }

  void _handleCheck() {
    if (_accuracy < 0.1) {
      _wobble.forward(from: 0);
      return;
    }
    final passed = _accuracy >= _passThreshold;
    setState(() {
      _checked = true;
      _passed = passed;
    });
    _click();
    if (passed) _clock.stop();
    if (!passed) {
      _failedChecks++;
      _wobble.forward(from: 0);
      Future.delayed(const Duration(milliseconds: 700), () {
        if (mounted) setState(() => _checked = false);
      });
    }
  }

  void _next() {
    _scores.add(_accuracy);
    if (_idx + 1 >= widget.cards.length) {
      _clock.stop();
      _watch.stop();
      _click();
      setState(() => _screen = _Screen.done);
      _enter.forward(from: 0);
    } else {
      setState(() {
        _idx += 1;
        _accuracy = 0.0;
        _checked = false;
        _passed = false;
      });
      _entrance.forward(from: 0);
      _clock.forward(from: 0);
      _say();
    }
  }

  int _clearCounter = 0;

  void _clear() {
    setState(() {
      _click();
      _accuracy = 0.0;
      _checked = false;
      _passed = false;
      _clearCounter++;
    });
    // A pass froze the timer; clearing to try again sets it running again.
    if (!_clock.isAnimating && _clock.value < 1) _clock.forward();
  }

  void _click() {
    if (_sound) SystemSound.play(SystemSoundType.click);
  }

  void _say() {
    if (!_sound) return;
    final asset = _card.audioAsset;
    if (asset != null && _audio != null) {
      unawaited(_audio!.playLetter(asset));
    } else {
      _click();
    }
  }

  void _toggleMusic() {
    setState(() => _music = !_music);
    if (_audio != null) unawaited(_audio!.setMusicEnabled(_music));
  }

  void _toggleSound() {
    setState(() => _sound = !_sound);
    if (!_sound && _audio != null) unawaited(_audio!.stopLetter());
  }

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    for (final n in _kAssets) {
      precacheImage(AssetImage('$_kA/$n.png'), context);
    }
  }

  @override
  void dispose() {
    if (_audio != null) unawaited(_audio!.dispose());
    _bgTicker.dispose();
    _bgT.dispose();
    _bgShader?.dispose();
    for (final i in _bgLayers ?? const <ui.Image>[]) {
      i.dispose();
    }
    _idle.dispose();
    _enter.dispose();
    _clock.dispose();
    _entrance.dispose();
    _breathe.dispose();
    _wobble.dispose();
    super.dispose();
  }

  static const _kA = 'assets/images/tracing';
  static const _kAssets = [
    'start_bg',
    'start_logo',
    'start_boy',
    'start_girl',
    'start_tray',
    'start_play',
    'start_play_down',
    'hud_stars',
    'hud_accuracy',
    'hud_card',
    'hud_timer',
    'btn_round',
    'btn_round_down',
    'game_clear',
    'game_clear_down',
    'game_check',
    'game_check_down',
    'game_tray',
  ];

  static const _kBrown = Color(0xFF4A2A0C);
  static const _kGreen = Color(0xFF1E8F4E);

  static TextStyle _f(double size, Color color) => TextStyle(
    fontFamily: 'Fredoka',
    fontWeight: FontWeight.w700,
    fontSize: size,
    color: color,
    height: 1.1,
  );

  // Stage for both screens, laid out in the reference mockups' own pixels.
  static const _kW = 853.0;
  static const _kH = 1844.0;

  /// Start screen's Play: on to How to Play.
  void _play() {
    _idle.stop();
    _click();
    setState(() {
      _screen = _Screen.howTo;
      _playDown = false;
    });
    _enter.forward(from: 0);
  }

  /// How to Play's Back: return to the start screen (not out of the lesson).
  void _toStart() {
    _click();
    if (_audio != null) unawaited(_audio!.stopLetter());
    setState(() => _screen = _Screen.start);
    _idle.repeat();
  }

  /// Into the tray, first letter, timer and round clock running.
  void _go() {
    _click();
    setState(() => _screen = _Screen.play);
    _entrance.forward(from: 0);
    _clock.forward(from: 0);
    _watch
      ..reset()
      ..start();
    _say();
  }

  /// The ending's Replay: same letters from the top.
  void _replay() {
    setState(() {
      _idx = 0;
      _scores.clear();
      _failedChecks = 0;
      _accuracy = 0;
      _checked = false;
      _passed = false;
      _clearCounter++;
    });
    _go();
  }

  double get _average =>
      _scores.isEmpty ? 0 : _scores.reduce((a, b) => a + b) / _scores.length;

  /// The ending's Continue: hand the round's result to the lesson.
  void _finish() {
    _click();
    if (_audio != null) unawaited(_audio!.stopLetter());
    widget.onComplete(widget.xp, _average * 100, _failedChecks);
  }

  Widget _at(double l, double t, double w, double h, Widget c) =>
      Positioned(left: l, top: t, width: w, height: h, child: c);

  Widget _img(String n) => Image.asset('$_kA/$n.png', fit: BoxFit.contain);

  /// Framed HUD art, drawn at 2x. Each piece is pre-rendered at its slot's
  /// exact shape, so nothing is stretched out of proportion here.
  Widget _frame(String n) =>
      Image.asset('$_kA/$n.png', scale: 2, fit: BoxFit.fill);

  /// Soft ground shadow of [c]'s own silhouette, nudged by [o].
  Widget _shadow(Widget c, Offset o) => IgnorePointer(
    child: Transform.translate(
      offset: o,
      child: ImageFiltered(
        imageFilter: ui.ImageFilter.blur(sigmaX: 10, sigmaY: 10),
        child: ColorFiltered(
          colorFilter: const ColorFilter.mode(
            Color(0x5C4A2A0C),
            BlendMode.srcIn,
          ),
          child: c,
        ),
      ),
    ),
  );

  /// Blurred contact pool where something meets the ground.
  Widget _pool(double l, double t, double w, double h) => _at(
    l,
    t,
    w,
    h,
    IgnorePointer(
      child: ImageFiltered(
        imageFilter: ui.ImageFilter.blur(sigmaX: 12, sigmaY: 6),
        child: DecoratedBox(
          decoration: BoxDecoration(
            color: const Color(0x664A2A0C),
            borderRadius: BorderRadius.all(Radius.elliptical(w / 2, h / 2)),
          ),
        ),
      ),
    ),
  );

  Widget _buildStart() {
    final topInset = MediaQuery.of(context).padding.top;
    final still = MediaQuery.of(context).disableAnimations;
    return Stack(
      fit: StackFit.expand,
      children: [
        _liveBg(),
        Padding(
          padding: EdgeInsets.only(top: topInset),
          child: FittedBox(
            child: SizedBox(
              width: _kW,
              height: _kH,
              child: Stack(
                children: [
                  // Mascots stand on the plaza: a soft silhouette thrown
                  // down-left plus a contact pool under the feet.
                  _at(
                    14,
                    532,
                    408,
                    607,
                    _shadow(_img('start_boy'), const Offset(-18, 12)),
                  ),
                  _at(
                    447,
                    583,
                    390,
                    599,
                    _shadow(_img('start_girl'), const Offset(-18, 12)),
                  ),
                  _pool(38, 1112, 360, 50),
                  _pool(470, 1156, 340, 50),
                  _at(14, 532, 408, 607, _img('start_boy')),
                  _at(447, 583, 390, 599, _img('start_girl')),
                  // Tray rests on the ground: drop shadow below and a
                  // darker contact band along its front edge.
                  _at(
                    27,
                    935,
                    800,
                    575,
                    _shadow(_img('start_tray'), const Offset(-10, 26)),
                  ),
                  _pool(47, 1470, 760, 64),
                  _at(27, 935, 800, 575, _img('start_tray')),
                  Positioned.fill(
                    child: AnimatedBuilder(
                      animation: _idle,
                      builder: (context, _) {
                        final t = still ? 0.0 : _idle.value * 2 * math.pi;
                        return Stack(
                          children: [
                            _at(
                              80,
                              32 + 8 * math.sin(t),
                              694,
                              509,
                              _img('start_logo'),
                            ),
                            _at(
                              110,
                              1482,
                              634,
                              265,
                              IgnorePointer(
                                child: CustomPaint(
                                  painter: _SparkPainter(
                                    .5 + .5 * math.sin(t * 2),
                                  ),
                                ),
                              ),
                            ),
                            _at(
                              186,
                              1512,
                              480,
                              205,
                              Semantics(
                                button: true,
                                label: 'Play',
                                child: GestureDetector(
                                  key: const ValueKey('trace-play'),
                                  behavior: HitTestBehavior.opaque,
                                  onTapDown: (_) =>
                                      setState(() => _playDown = true),
                                  onTapUp: (_) =>
                                      setState(() => _playDown = false),
                                  onTapCancel: () =>
                                      setState(() => _playDown = false),
                                  onTap: _play,
                                  child: Transform.scale(
                                    scale: _playDown
                                        ? .96
                                        : 1 + .03 * math.sin(t * 2),
                                    child: _img(
                                      _playDown
                                          ? 'start_play_down'
                                          : 'start_play',
                                    ),
                                  ),
                                ),
                              ),
                            ),
                          ],
                        );
                      },
                    ),
                  ),
                ],
              ),
            ),
          ),
        ),
      ],
    );
  }

  @override
  Widget build(BuildContext context) {
    switch (_screen) {
      case _Screen.start:
        return _buildStart();
      case _Screen.howTo:
        return _stage(_buildHowTo());
      case _Screen.done:
        return _stage(_buildDone());
      case _Screen.play:
        break;
    }
    final topInset = MediaQuery.of(context).padding.top;
    return LayoutBuilder(
      builder: (context, box) {
        final h = box.maxHeight - topInset;
        final s = math.min(box.maxWidth / _kW, h / _kH);
        final ox = (box.maxWidth - _kW * s) / 2;
        final oy = topInset + (h - _kH * s) / 2;
        // Screen-space twin of [_at] for layers kept outside the stage.
        Widget place(double l, double t, double w, double hh, Widget c) =>
            Positioned(
              left: ox + l * s,
              top: oy + t * s,
              width: w * s,
              height: hh * s,
              child: c,
            );
        return Stack(
          fit: StackFit.expand,
          children: [
            _liveBg(),
            Padding(
              padding: EdgeInsets.only(top: topInset),
              child: FittedBox(
                child: SizedBox(width: _kW, height: _kH, child: _buildHud()),
              ),
            ),
            // Traced in screen pixels rather than inside the scaled stage,
            // so ink width and tolerances match the device.
            // Over the sand only, and clipped to it: nothing drawn while
            // tracing can land on the frame or beyond.
            place(
              109,
              944,
              _kSandW,
              _kSandH,
              ClipPath(clipper: _SandClip(), child: _buildCanvas()),
            ),
          ],
        );
      },
    );
  }

  Widget _roundBtn(String key, IconData icon, VoidCallback onTap) => _PressImg(
    key: ValueKey(key),
    asset: '$_kA/btn_round',
    lift: 4.5,
    onTap: onTap,
    child: Icon(icon, size: 58, color: _kBrown),
  );

  Widget _buildHud() {
    final last = _idx + 1 >= widget.cards.length;
    final stars = _idx + (_passed ? 1 : 0);
    return Stack(
      children: [
        _at(
          45,
          60,
          105,
          105,
          _roundBtn(
            'trace-back',
            Icons.arrow_back_ios_new_rounded,
            widget.onBack,
          ),
        ),
        _at(
          185,
          68,
          205,
          84,
          Stack(
            fit: StackFit.expand,
            children: [
              _frame('hud_stars'),
              Row(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  const Icon(
                    Icons.star_rounded,
                    size: 48,
                    color: Color(0xFFF4B400),
                  ),
                  const SizedBox(width: 10),
                  Text('$stars', style: _f(36, _kBrown)),
                ],
              ),
            ],
          ),
        ),
        _at(
          585,
          60,
          105,
          105,
          _roundBtn(
            'trace-music',
            _music ? Icons.music_note_rounded : Icons.music_off_rounded,
            _toggleMusic,
          ),
        ),
        _at(
          712,
          60,
          105,
          105,
          _roundBtn(
            'trace-sound',
            _sound ? Icons.volume_up_rounded : Icons.volume_off_rounded,
            _toggleSound,
          ),
        ),
        Positioned.fill(
          child: AnimatedBuilder(
            animation: _clock,
            builder: (context, _) {
              final left = 1 - _clock.value;
              final secs = (_kSeconds * left).ceil();
              return Stack(
                children: [
                  _at(
                    297,
                    198,
                    263,
                    80,
                    Stack(
                      fit: StackFit.expand,
                      children: [
                        _frame('hud_timer'),
                        Row(
                          mainAxisAlignment: MainAxisAlignment.center,
                          children: [
                            const Icon(
                              Icons.hourglass_bottom_rounded,
                              size: 40,
                              color: Color(0xFFC98A1A),
                            ),
                            const SizedBox(width: 18),
                            Text(
                              '0:${secs.toString().padLeft(2, '0')}',
                              style: _f(36, _kBrown),
                            ),
                          ],
                        ),
                      ],
                    ),
                  ),
                  _at(
                    215,
                    283,
                    422,
                    28,
                    Container(
                      padding: const EdgeInsets.all(4),
                      decoration: BoxDecoration(
                        color: const Color(0xFFFFF3D6),
                        borderRadius: BorderRadius.circular(14),
                        border: Border.all(
                          color: const Color(0xFFE7A92B),
                          width: 3,
                        ),
                      ),
                      alignment: Alignment.centerLeft,
                      child: FractionallySizedBox(
                        widthFactor: left,
                        heightFactor: 1,
                        child: DecoratedBox(
                          decoration: BoxDecoration(
                            borderRadius: BorderRadius.circular(8),
                            gradient: const LinearGradient(
                              colors: [Color(0xFF2FAE5B), Color(0xFF7BD37F)],
                            ),
                          ),
                        ),
                      ),
                    ),
                  ),
                ],
              );
            },
          ),
        ),
        _at(
          207,
          335,
          438,
          187,
          Stack(
            fit: StackFit.expand,
            children: [
              _frame('hud_card'),
              Padding(
                padding: const EdgeInsets.fromLTRB(56, 24, 44, 24),
                child: Row(
                  children: [
                    Expanded(
                      child: Column(
                        mainAxisAlignment: MainAxisAlignment.center,
                        children: [
                          Text('TRACE THIS', style: _f(26, _kBrown)),
                          Flexible(
                            child: FittedBox(
                              // The character itself, in the same naskh face
                              // the sand's letter is cut from.
                              child: Text(
                                _letter,
                                textDirection: TextDirection.rtl,
                                style: const TextStyle(
                                  fontFamily: 'ScheherazadeNew',
                                  fontWeight: FontWeight.w700,
                                  fontSize: 84,
                                  height: 1.25,
                                  color: _kBrown,
                                ),
                              ),
                            ),
                          ),
                        ],
                      ),
                    ),
                    Semantics(
                      button: true,
                      label: 'Hear the letter',
                      child: GestureDetector(
                        key: const ValueKey('trace-say'),
                        onTap: _say,
                        child: _speaker(104),
                      ),
                    ),
                  ],
                ),
              ),
            ],
          ),
        ),
        _at(
          60,
          772,
          732,
          80,
          Stack(
            fit: StackFit.expand,
            children: [
              _frame('hud_accuracy'),
              Padding(
                padding: const EdgeInsets.symmetric(horizontal: 60),
                child: Row(
                  children: [
                    Text('Accuracy', style: _f(28, _kBrown)),
                    const SizedBox(width: 22),
                    Expanded(
                      child: Container(
                        height: 30,
                        decoration: BoxDecoration(
                          color: const Color(0xFFEFE3C8),
                          borderRadius: BorderRadius.circular(15),
                        ),
                        alignment: Alignment.centerLeft,
                        child: AnimatedFractionallySizedBox(
                          duration: const Duration(milliseconds: 120),
                          widthFactor: _accuracy.clamp(0.0, 1.0),
                          heightFactor: 1,
                          child: DecoratedBox(
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(15),
                              gradient: const LinearGradient(
                                colors: [Color(0xFF1E8F4E), Color(0xFF3FBF6A)],
                              ),
                            ),
                          ),
                        ),
                      ),
                    ),
                    const SizedBox(width: 20),
                    SizedBox(
                      width: 76,
                      child: Text(
                        '${(_accuracy * 100).clamp(0, 100).round()}%',
                        textAlign: TextAlign.right,
                        style: _f(30, _kGreen),
                      ),
                    ),
                  ],
                ),
              ),
            ],
          ),
        ),
        // Tray rests on the plaza like on the start screen.
        _at(18, 870, 820, 655, _shadow(_tray(), const Offset(-10, 26))),
        _pool(38, 1480, 780, 64),
        _at(18, 870, 820, 655, _tray()),
        Positioned(
          left: 0,
          right: 0,
          top: 1537,
          height: 52,
          child: Center(child: _dots()),
        ),
        _at(
          30,
          1635,
          258,
          120,
          _creamBtn('trace-clear', 'Clear', Icons.refresh_rounded, _clear),
        ),
        _at(
          310,
          1625,
          512,
          140,
          _greenBtn(
            'trace-check',
            _passed ? (last ? 'Done!' : 'Next') : 'Check my trace',
            _passed ? Icons.arrow_forward_rounded : Icons.check_rounded,
            _passed ? _next : _handleCheck,
          ),
        ),
      ],
    );
  }

  /// A full-screen page laid out on the 853x1844 stage over the live
  /// courtyard.
  Widget _stage(Widget child) => Stack(
    fit: StackFit.expand,
    children: [
      _liveBg(),
      Padding(
        padding: EdgeInsets.only(top: MediaQuery.of(context).padding.top),
        child: FittedBox(
          child: SizedBox(width: _kW, height: _kH, child: child),
        ),
      ),
    ],
  );

  /// The green "hear it" disc from the Trace This card.
  Widget _speaker(double size) => Container(
    width: size,
    height: size,
    decoration: BoxDecoration(
      shape: BoxShape.circle,
      gradient: const LinearGradient(
        begin: Alignment.topCenter,
        end: Alignment.bottomCenter,
        colors: [Color(0xFF2FAE5B), Color(0xFF137A3E)],
      ),
      border: Border.all(color: const Color(0xFFBFE8C4), width: size * .05),
    ),
    child: Icon(Icons.volume_up_rounded, size: size * .52, color: Colors.white),
  );

  /// The flat green disc with a white icon that leads the green button.
  Widget _disc(IconData icon, double size) => Container(
    width: size,
    height: size,
    decoration: BoxDecoration(
      shape: BoxShape.circle,
      color: const Color(0xFF2FAE5B),
      border: Border.all(color: const Color(0xFFE8F8EA), width: size * .07),
    ),
    child: Icon(icon, size: size * .64, color: Colors.white),
  );

  /// The big green button (512x140 slot).
  Widget _greenBtn(String key, String label, IconData icon, VoidCallback on) =>
      _PressImg(
        key: ValueKey(key),
        asset: '$_kA/game_check',
        lift: 6,
        onTap: on,
        child: Row(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            _disc(icon, 72),
            const SizedBox(width: 18),
            Flexible(
              child: FittedBox(
                fit: BoxFit.scaleDown,
                child: Text(label, style: _f(38, Colors.white)),
              ),
            ),
          ],
        ),
      );

  /// The cream button (258x120 slot).
  Widget _creamBtn(String key, String label, IconData icon, VoidCallback on) =>
      _PressImg(
        key: ValueKey(key),
        asset: '$_kA/game_clear',
        lift: 8,
        onTap: on,
        child: Row(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Icon(icon, size: 48, color: _kBrown),
            const SizedBox(width: 10),
            Text(label, style: _f(36, _kBrown)),
          ],
        ),
      );

  /// Soft cream panel with the HUD's gold rim.
  static BoxDecoration _panel(double radius) => BoxDecoration(
    color: const Color(0xFFFFF6E0),
    borderRadius: BorderRadius.circular(radius),
    border: Border.all(color: const Color(0xFFE7A92B), width: 5),
    boxShadow: const [
      BoxShadow(color: Color(0x404A2A0C), blurRadius: 18, offset: Offset(0, 8)),
    ],
  );

  /// Eases a child in (rising, fading) over [from]..[to] of [_enter].
  Widget _rise(double from, double to, Widget child) => AnimatedBuilder(
    animation: _enter,
    builder: (context, c) {
      final t = Curves.easeOutBack.transform(
        ((_enter.value - from) / (to - from)).clamp(0.0, 1.0),
      );
      return Opacity(
        opacity: t.clamp(0.0, 1.0),
        child: Transform.translate(offset: Offset(0, 40 * (1 - t)), child: c),
      );
    },
    child: child,
  );

  /// The title plaque both new screens open with.
  Widget _plaque(String title, String sub) => Stack(
    fit: StackFit.expand,
    children: [
      _frame('hud_card'),
      Padding(
        padding: const EdgeInsets.fromLTRB(50, 30, 50, 34),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            FittedBox(child: Text(title, style: _f(56, _kGreen))),
            const SizedBox(height: 6),
            FittedBox(child: Text(sub, style: _f(28, _kBrown))),
          ],
        ),
      ),
    ],
  );

  /// How to Play: three illustrated steps, then Let's Go.
  Widget _buildHowTo() {
    final body = _f(28, _kBrown).copyWith(fontWeight: FontWeight.w400);
    Widget step(int n, String title, String text, Widget art) => Container(
      padding: const EdgeInsets.all(24),
      decoration: _panel(40),
      child: Row(
        children: [
          Container(
            width: 200,
            height: 200,
            alignment: Alignment.center,
            decoration: BoxDecoration(
              color: const Color(0xFFF7E7C4),
              borderRadius: BorderRadius.circular(30),
            ),
            child: art,
          ),
          const SizedBox(width: 28),
          Expanded(
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Row(
                  children: [
                    Container(
                      width: 54,
                      height: 54,
                      alignment: Alignment.center,
                      decoration: const BoxDecoration(
                        shape: BoxShape.circle,
                        color: Color(0xFFF4B400),
                      ),
                      child: Text('$n', style: _f(32, Colors.white)),
                    ),
                    const SizedBox(width: 14),
                    Text(title, style: _f(42, _kGreen)),
                  ],
                ),
                const SizedBox(height: 12),
                Text(text, style: body),
              ],
            ),
          ),
        ],
      ),
    );

    return Stack(
      children: [
        _at(
          45,
          60,
          105,
          105,
          _roundBtn(
            'trace-howto-back',
            Icons.arrow_back_ios_new_rounded,
            _toStart,
          ),
        ),
        _at(
          190,
          110,
          473,
          204,
          _rise(0, .35, _plaque('How to Play', 'Magic Sand Tracer')),
        ),
        _at(
          50,
          400,
          753,
          260,
          _rise(
            .15,
            .5,
            step(
              1,
              'Listen',
              'Tap the speaker to hear the letter.',
              _speaker(120),
            ),
          ),
        ),
        _at(
          50,
          700,
          753,
          260,
          _rise(
            .3,
            .65,
            step(
              2,
              'Trace',
              'Start at number 1 and follow the letter from right to left.',
              ValueListenableBuilder<double>(
                valueListenable: _bgT,
                builder: (context, t, _) => CustomPaint(
                  size: const Size(170, 170),
                  painter: _DemoPainter(t),
                ),
              ),
            ),
          ),
        ),
        _at(
          50,
          1000,
          753,
          260,
          _rise(
            .45,
            .8,
            step(
              3,
              'Check',
              'Fill the whole letter, then tap Check my trace.',
              _disc(Icons.check_rounded, 120),
            ),
          ),
        ),
        _at(
          170,
          1330,
          512,
          140,
          _rise(
            .6,
            1,
            _greenBtn('trace-go', "Let's Go!", Icons.play_arrow_rounded, _go),
          ),
        ),
      ],
    );
  }

  /// The ending: congratulations, stars for the round, each letter's
  /// accuracy and the round's totals, then Continue or Replay.
  Widget _buildDone() {
    final avg = _average;
    final stars = avg >= .9 ? 3 : (avg >= .8 ? 2 : 1);
    final secs = _watch.elapsed.inSeconds;
    final time = '${secs ~/ 60}:${(secs % 60).toString().padLeft(2, '0')}';

    Widget star(int i, double size) {
      final on = i < stars;
      return AnimatedBuilder(
        animation: _enter,
        builder: (context, _) {
          final t = Curves.elasticOut.transform(
            ((_enter.value - .25 - i * .15) / .45).clamp(0.0, 1.0),
          );
          return Transform.scale(
            scale: t,
            child: Stack(
              alignment: Alignment.center,
              children: [
                Icon(Icons.star_rounded, size: size + 16, color: _kBrown),
                Icon(
                  Icons.star_rounded,
                  size: size,
                  color: on ? const Color(0xFFF4B400) : const Color(0xFFD9CFC0),
                ),
              ],
            ),
          );
        },
      );
    }

    Widget tile(int i) {
      final card = widget.cards[i];
      final letter = card.arabic.split('\n').last.trim();
      final score = i < _scores.length ? _scores[i] : 0.0;
      return Container(
        width: 150,
        height: 170,
        decoration: BoxDecoration(
          color: const Color(0xFFFFFBEF),
          borderRadius: BorderRadius.circular(26),
          border: Border.all(color: const Color(0xFFF1DDB0), width: 3),
        ),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Text(
              letter,
              textDirection: TextDirection.rtl,
              style: const TextStyle(
                fontFamily: 'ScheherazadeNew',
                fontWeight: FontWeight.w700,
                fontSize: 64,
                height: 1.2,
                color: _kBrown,
              ),
            ),
            Text(
              '${(score * 100).round()}%',
              style: _f(26, score >= .9 ? _kGreen : const Color(0xFFC98A1A)),
            ),
          ],
        ),
      );
    }

    Widget stat(IconData icon, String value, String label) => Column(
      mainAxisSize: MainAxisSize.min,
      children: [
        Row(
          mainAxisSize: MainAxisSize.min,
          children: [
            Icon(icon, size: 40, color: const Color(0xFFC98A1A)),
            const SizedBox(width: 8),
            Text(value, style: _f(38, _kBrown)),
          ],
        ),
        const SizedBox(height: 4),
        Text(
          label,
          style: _f(24, _kBrown).copyWith(fontWeight: FontWeight.w400),
        ),
      ],
    );

    return Stack(
      children: [
        _at(
          190,
          90,
          473,
          204,
          _rise(0, .3, _plaque('Mumtaz!', 'You traced every letter!')),
        ),
        _at(10, 330, 200, 297, _rise(.1, .45, _img('start_boy'))),
        _at(643, 330, 200, 307, _rise(.1, .45, _img('start_girl'))),
        Positioned(
          left: 0,
          right: 0,
          top: 350,
          height: 200,
          child: Row(
            mainAxisAlignment: MainAxisAlignment.center,
            crossAxisAlignment: CrossAxisAlignment.end,
            children: [
              star(0, 110),
              Padding(
                padding: const EdgeInsets.only(bottom: 40),
                child: star(1, 140),
              ),
              star(2, 110),
            ],
          ),
        ),
        _at(
          40,
          690,
          773,
          660,
          _rise(
            .45,
            .8,
            Container(
              padding: const EdgeInsets.fromLTRB(30, 26, 30, 26),
              decoration: _panel(44),
              child: Column(
                children: [
                  Text('Your Letters', style: _f(40, _kBrown)),
                  const SizedBox(height: 20),
                  Wrap(
                    textDirection: TextDirection.rtl,
                    alignment: WrapAlignment.center,
                    spacing: 18,
                    runSpacing: 18,
                    children: [
                      for (var i = 0; i < widget.cards.length; i++) tile(i),
                    ],
                  ),
                  const Spacer(),
                  Row(
                    mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                    children: [
                      stat(
                        Icons.edit_rounded,
                        '${_scores.length}/${widget.cards.length}',
                        'letters',
                      ),
                      stat(
                        Icons.track_changes_rounded,
                        '${(avg * 100).round()}%',
                        'accuracy',
                      ),
                      stat(Icons.hourglass_bottom_rounded, time, 'time'),
                    ],
                  ),
                ],
              ),
            ),
          ),
        ),
        _at(
          170,
          1400,
          512,
          140,
          _rise(
            .6,
            .9,
            _greenBtn(
              'trace-continue',
              'Continue',
              Icons.arrow_forward_rounded,
              _finish,
            ),
          ),
        ),
        _at(
          297,
          1570,
          258,
          120,
          _rise(
            .7,
            1,
            _creamBtn('trace-replay', 'Replay', Icons.replay_rounded, _replay),
          ),
        ),
        Positioned.fill(
          child: IgnorePointer(
            child: ValueListenableBuilder<double>(
              valueListenable: _bgT,
              builder: (context, t, _) =>
                  CustomPaint(painter: _ConfettiPainter(t)),
            ),
          ),
        ),
      ],
    );
  }

  Widget _tray() =>
      Image.asset('$_kA/game_tray.png', scale: 1.5, fit: BoxFit.fill);

  /// Letter progress: done green, current long gold, the rest grey.
  Widget _dots() => Container(
    padding: const EdgeInsets.symmetric(horizontal: 18, vertical: 12),
    decoration: BoxDecoration(
      color: const Color(0xFFFFF6E0),
      borderRadius: BorderRadius.circular(26),
      border: Border.all(color: const Color(0xFFF1DDB0), width: 3),
      boxShadow: const [
        BoxShadow(
          color: Color(0x264A2A0C),
          blurRadius: 8,
          offset: Offset(0, 3),
        ),
      ],
    ),
    child: Row(
      mainAxisSize: MainAxisSize.min,
      children: [
        for (var i = 0; i < widget.cards.length; i++) ...[
          if (i != 0) const SizedBox(width: 12),
          AnimatedContainer(
            duration: const Duration(milliseconds: 300),
            width: i == _idx ? 44 : 22,
            height: 22,
            decoration: BoxDecoration(
              color: i < _idx
                  ? _kGreen
                  : i == _idx
                  ? const Color(0xFFF4C430)
                  : const Color(0xFFD9CFC0),
              borderRadius: BorderRadius.circular(11),
            ),
          ),
        ],
      ],
    ),
  );

  Widget _buildCanvas() {
    return AnimatedBuilder(
      animation: Listenable.merge([_entrance, _wobble]),
      builder: (context, child) {
        final e = _overshoot.transform(_entrance.value);
        final wobbleT = Curves.easeInOut.transform(_wobble.value);
        final dx = _wobble.isAnimating
            ? (wobbleT < 0.5 ? -6.0 : 6.0) * (1 - (wobbleT - 0.5).abs() * 2)
            : 0.0;
        return Opacity(
          opacity: e.clamp(0.0, 1.0),
          child: Transform.translate(
            offset: Offset(dx, 12 * (1 - e)),
            child: child,
          ),
        );
      },
      child: LetterTraceCanvas(
        key: ValueKey('${_card.id}_${_idx}_$_clearCounter'),
        passed: _checked && _passed,
        failed: _checked && !_passed,
        breathe: _breathe,
        guidePointsBuilder: _guideStrokes,
        onStroke: _handleStroke,
        onDirectionViolation: () {
          _wobble.forward(from: 0);
        },
        // The canvas is laid out in screen pixels: a finger anywhere inside
        // the letter's stroke fills it in.
        coverTolerance: 18,
        glyphBuilder: _glyph,
      ),
    );
  }
}

/// Clips the tracing canvas to the tray's sand.
class _SandClip extends CustomClipper<Path> {
  @override
  Path getClip(Size size) => _TraceActivityState._sand(size);

  @override
  bool shouldReclip(_SandClip old) => false;
}

enum _Screen { start, howTo, play, done }

/// How to Play's step 2: ب traced on a loop — the letter pressed into the
/// sand, gold filling it from the number-1 start, a fingertip leading.
class _DemoPainter extends CustomPainter {
  _DemoPainter(this.t);

  /// Seconds; one trace every 3s, holding the finished letter a moment.
  final double t;

  @override
  void paint(Canvas canvas, Size size) {
    final trace = letterTraces['ب']!;
    final scale = size.shortestSide * .92;
    final off = Offset(
      (size.width - scale) / 2,
      (size.height - scale) / 2 - size.height * .06,
    );
    Offset at(double x, double y) => off + Offset(x * scale, y * scale);
    final glyph = Path();
    for (final c in trace.outline) {
      glyph.addPolygon([
        for (var i = 0; i < c.length; i += 2) at(c[i], c[i + 1]),
      ], true);
    }
    final body = trace.strokes.first;
    final pts = [
      for (var i = 0; i < body.length; i += 2) at(body[i], body[i + 1]),
    ];
    final p = ((t % 3) / 2.2).clamp(0.0, 1.0);
    final upto = (p * (pts.length - 1)).round();

    canvas.drawPath(glyph, Paint()..color = const Color(0x554A3A1E));
    final bounds = Offset.zero & size;
    canvas.saveLayer(bounds, Paint());
    if (upto > 0) {
      canvas.drawPath(
        Path()..addPolygon(pts.sublist(0, upto + 1), false),
        Paint()
          ..color = const Color(0xFFF4B400)
          ..style = PaintingStyle.stroke
          ..strokeWidth = scale * .16
          ..strokeCap = StrokeCap.round
          ..strokeJoin = StrokeJoin.round,
      );
    }
    canvas.drawPath(glyph, Paint()..blendMode = BlendMode.dstIn);
    canvas.restore();

    // Number 1 at the start, then the fingertip.
    canvas.drawCircle(pts.first, 11, Paint()..color = const Color(0xFF4A3A1E));
    final tp = TextPainter(
      text: const TextSpan(
        text: '1',
        style: TextStyle(
          fontSize: 13,
          fontWeight: FontWeight.w800,
          color: Colors.white,
        ),
      ),
      textDirection: TextDirection.ltr,
    )..layout();
    tp.paint(canvas, pts.first - Offset(tp.width / 2, tp.height / 2));
    final tip = pts[upto];
    canvas.drawCircle(
      tip + const Offset(0, 3),
      14,
      Paint()
        ..color = const Color(0x55000000)
        ..maskFilter = const MaskFilter.blur(BlurStyle.normal, 4),
    );
    canvas.drawCircle(tip, 13, Paint()..color = Colors.white);
    canvas.drawCircle(
      tip,
      13,
      Paint()
        ..color = const Color(0xFF2FAE5B)
        ..style = PaintingStyle.stroke
        ..strokeWidth = 4,
    );
  }

  @override
  bool shouldRepaint(_DemoPainter old) => old.t != t;
}

/// The ending's confetti: paper bits drifting down on a loop, each
/// fluttering (its width flipping as it tumbles) and swaying as it falls.
class _ConfettiPainter extends CustomPainter {
  _ConfettiPainter(this.t);

  final double t;

  static const _colors = [
    Color(0xFFF4B400),
    Color(0xFF2FAE5B),
    Color(0xFFFF7A59),
    Color(0xFF3BB6E8),
    Color(0xFFFFFFFF),
  ];

  @override
  void paint(Canvas canvas, Size size) {
    double h(int i, int k) {
      final v = math.sin(i * 12.9898 + k * 78.233) * 43758.5453;
      return v - v.floorToDouble();
    }

    for (var i = 0; i < 70; i++) {
      final fall = 120 + 160 * h(i, 1);
      final y = (h(i, 2) * size.height + t * fall) % (size.height + 60) - 30;
      final x = h(i, 3) * size.width + 30 * math.sin(t * (1 + h(i, 4)) + i);
      final flip = math.cos(t * (3 + 4 * h(i, 5)) + i);
      canvas.save();
      canvas.translate(x, y);
      canvas.rotate(t * (1 + 2 * h(i, 6)) + i);
      canvas.drawRect(
        Rect.fromCenter(
          center: Offset.zero,
          width: 22 * flip.abs() + 2,
          height: 12,
        ),
        Paint()..color = _colors[i % _colors.length],
      );
      canvas.restore();
    }
  }

  @override
  bool shouldRepaint(_ConfettiPainter old) => old.t != t;
}

/// The wind over the courtyard, 0.24-1: a slow swell with a quicker gust on
/// top, so every plant leans with the same weather.
double _gust(double t) =>
    0.62 + 0.25 * math.sin(0.23 * t) + 0.13 * math.sin(0.61 * t + 1.7);

/// The live backdrop, drawn by `shaders/sand_tracer_bg.frag` from [layers]
/// (clean, palms, field, aux, clouds) at [t] seconds.
class _LiveBgPainter extends CustomPainter {
  _LiveBgPainter(this.shader, this.layers, this.t);

  final ui.FragmentShader shader;
  final List<ui.Image> layers;
  final double t;

  @override
  void paint(Canvas canvas, Size size) {
    shader
      ..setFloat(0, size.width)
      ..setFloat(1, size.height)
      ..setFloat(2, t)
      ..setFloat(3, _gust(t));
    for (var i = 0; i < layers.length; i++) {
      shader.setImageSampler(i, layers[i]);
    }
    canvas.drawRect(Offset.zero & size, Paint()..shader = shader);
  }

  @override
  bool shouldRepaint(_LiveBgPainter old) => old.t != t;
}

/// Yellow shine dashes fanning out from the Play button's top corners;
/// [glow] 0..1 pulses their opacity.
class _SparkPainter extends CustomPainter {
  _SparkPainter(this.glow);

  final double glow;

  @override
  void paint(Canvas canvas, Size size) {
    final paint = Paint()
      ..color = const Color(0xFFFFD84A).withValues(alpha: .45 + .55 * glow)
      ..strokeWidth = 9
      ..strokeCap = StrokeCap.round;
    for (final side in [-1.0, 1.0]) {
      final c = Offset(
        size.width / 2 + side * size.width * .40,
        size.height * .30,
      );
      for (final a in [-.35, .15, .65]) {
        final dir = Offset(side * math.cos(a), -math.sin(a));
        canvas.drawLine(c + dir * 40, c + dir * 68, paint);
      }
    }
  }

  @override
  bool shouldRepaint(_SparkPainter old) => old.glow != glow;
}

/// Image button that swaps to its `_down` art while held; [child] (icon or
/// label) sits centred on the raised face and dips a touch with the press.
class _PressImg extends StatefulWidget {
  const _PressImg({
    super.key,
    required this.asset,
    required this.onTap,
    required this.child,
    this.lift = 0,
  });

  final String asset;
  final VoidCallback onTap;
  final Widget child;

  /// How far the art's raised face sits above the image's centre (the lip
  /// and shadow are below it), so [child] centres on the face.
  final double lift;

  @override
  State<_PressImg> createState() => _PressImgState();
}

class _PressImgState extends State<_PressImg> {
  bool _down = false;

  void _set(bool v) {
    if (_down != v) setState(() => _down = v);
  }

  @override
  Widget build(BuildContext context) => Semantics(
    button: true,
    child: GestureDetector(
      behavior: HitTestBehavior.opaque,
      onTapDown: (_) => _set(true),
      onTapUp: (_) => _set(false),
      onTapCancel: () => _set(false),
      onTap: widget.onTap,
      child: Stack(
        fit: StackFit.expand,
        children: [
          Image.asset(
            '${widget.asset}${_down ? '_down' : ''}.png',
            scale: 2,
            fit: BoxFit.fill,
          ),
          Transform.translate(
            offset: Offset(0, -widget.lift + (_down ? 1 : 0)),
            child: widget.child,
          ),
        ],
      ),
    ),
  );
}
