// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRyGa1YMut5KaO7fS-BUcglwWjOG12jMY',
    appId: '1:872626440680:web:ab9fc267ff83c1d220fc5d',
    messagingSenderId: '872626440680',
    projectId: 'salamlearn-55712',
    authDomain: 'salamlearn-55712.firebaseapp.com',
    storageBucket: 'salamlearn-55712.firebasestorage.app',
    measurementId: 'G-9WNB06WFKT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKCr-Bv9DlWmDDS117khbO_FJZXQ599MU',
    appId: '1:872626440680:android:c4311bf5f45d70a120fc5d',
    messagingSenderId: '872626440680',
    projectId: 'salamlearn-55712',
    storageBucket: 'salamlearn-55712.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzycLJFLnhKSz_dXUxZeTsWfcXIFry5Cg',
    appId: '1:872626440680:ios:090d8befa8c7f2cc20fc5d',
    messagingSenderId: '872626440680',
    projectId: 'salamlearn-55712',
    storageBucket: 'salamlearn-55712.firebasestorage.app',
    iosBundleId: 'com.example.prjct',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzycLJFLnhKSz_dXUxZeTsWfcXIFry5Cg',
    appId: '1:872626440680:ios:090d8befa8c7f2cc20fc5d',
    messagingSenderId: '872626440680',
    projectId: 'salamlearn-55712',
    storageBucket: 'salamlearn-55712.firebasestorage.app',
    iosBundleId: 'com.example.prjct',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRyGa1YMut5KaO7fS-BUcglwWjOG12jMY',
    appId: '1:872626440680:web:d4ac2fe47c3e8a3120fc5d',
    messagingSenderId: '872626440680',
    projectId: 'salamlearn-55712',
    authDomain: 'salamlearn-55712.firebaseapp.com',
    storageBucket: 'salamlearn-55712.firebasestorage.app',
    measurementId: 'G-59ED39T136',
  );
}
