import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:firebase_core/firebase_core.dart'; // New

import 'data/local/hive_boxes.dart';
import 'firebase_options.dart'; // New (Generated by the command above)
import 'logic/router/app_router.dart';
import 'ui/theme/app_theme.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase before the app boots up
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  // Local-first persistence (Hive) — must be ready before any provider
  // reads/writes a box.
  await HiveService.init();

  await SystemChrome.setPreferredOrientations([
    DeviceOrientation.portraitUp,
    DeviceOrientation.portraitDown,
  ]);

  // Parent/Teacher (and every other admin/onboarding screen) keep the
  // normal system status + navigation bars. Only the Learner Hub goes
  // fullscreen immersive — see `HubShell`'s own SystemChrome calls, which
  // switch into immersiveSticky on entry and restore this default on exit.
  await SystemChrome.setEnabledSystemUIMode(SystemUiMode.edgeToEdge);

  runApp(const ProviderScope(child: SalamLearnApp()));
}

class SalamLearnApp extends ConsumerWidget {
  const SalamLearnApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return MaterialApp.router(
      title: 'SalamLearn',
      debugShowCheckedModeBanner: false,
      theme: AppTheme.light(),
      routerConfig: ref.watch(routerProvider),
    );
  }
}
